<?php  include('nav.php'); ?>
<!DOCTYPE html>
<html lang="en">

<
<body>
  <div class="container-fluid px-4">
		<div class="row justify-content-center mb-2 pb-2">
      <div class="col-md-8 text-center heading-section ftco-animate">
          <h2 class="mb-4"><span>Ph.Ds Produced Last </span> 10 Years</h2>
      </div>
    </div>	
  </div>  
    <div class="div1 ml-3 mr-3 mb-3">
        <table>
            <tbody>
            <tr>
    <td colspan="20"><table width="100%" cellspacing="0" cellpadding="0" bordercolor="#000000" border="2" >
      <tbody>
        <tr>
          <td><table width="100%" cellspacing="0" cellpadding="0">
                <tbody><tr>
                  <td valign="top" height="0" align="center">
				  





		<br>
<table style="width: 90%;"><tbody><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: center; width: 90%;">Name</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: center;">PhD Awarded Date</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: center; width: 90%;">Title</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: center; width: 90%;">Research Guide
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">RENU GEORGE</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">10/12/2021</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Software Design Consistency Checking of UML Models using Artificial Intelligence Techniques</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr Philip Samuel
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">NAMITHA . K</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">8/9/2021</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Learning Concept Drift and Recurrence from Data Streams: A Clustering Approach</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr G Santhosh Kumar
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">MARY PRIYA SEBASTIAN</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">7/28/2021</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">An Improved Phrase-Based English-Malayalam Machine Translation System Using Refined Bilingual Alignments</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr G Santhosh Kumar
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">VIPIN KUMAR K.S</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">8/18/2020</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Compiler Based Model Construction for Prioritized Test Scenario Generation and its Distributed Testing in Object Oriented Programs</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr Sheena Mathew
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">AJEES A.P</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">6/16/2020</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Design and Development of an Integrated Framework for  Pronominal Anaphora Resolution in Malayalam</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr Sumam Mary Idicula
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">SARITHA S</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">5/28/2020</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Mining Colocation Patterns and Change Detection in Spatiotemporal Data: A Tensor Factorization Approach</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr G Santhosh Kumar
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">PRIME KUMAR</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2/13/2020</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">DESIGN AND DEVELOPMENT  OF SPEECH AND HANDWRITING BASED INTERFACE FOR REAL TIME INTERACTION WITH COMPUTER IN MALAYALAM  </div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr Sumam Mary Idicula , Dr David Peter S
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">ASHA DAS</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">1/15/2020</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Automated Nuclear Pleomorphism Scoring in Histopathological Breast Cancer Images </div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr David Peter S , Dr MSN
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">SUNITHA E.V</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">11/12/2019</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Automatic Code Generation From UML Behavioural Models</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr Philip Samuel
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">MINI U</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">4/26/2019</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Mapping Information Diffusion through Social Computing for Knowledge Discovery</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr K Paulose Jacob
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">SINDHU.L</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">1/18/2019</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">An Integrated Approach For Plagiarism Detection in Malayalam Document</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr Sumam Mary Idicula
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">LINY VARGHESE</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">8/17/2018</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">An Integrated approach to  spam filtering and incremental updation of spam corpus using data mining techniques with modified spell correction algorithm </div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr K Paulose Jacob
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">THRESIAMMA K GEORGE</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">8/17/2018</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Security Vulnerability in on-line applications: Analysis , Anomaly Detection and Prevention of attack</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr K Paulose Jacob
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">JISHA P ABRAHAM</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">8/6/2018</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">AN ALGORITHMIC APPROACH FOR OPTIMIZING PAGE FAULT TO INCREASE PROCESSOR PERFORMANCE ALONG WITH THREAD-LEVEL SPECULATION</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr Philip Samuel
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">PREETHA  K.G</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">4/7/2018</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">DESIGN , DEVELOPMENT AND EVALUATION OF EFFICIENT ROUTING ALGORITHAMS FOR MOBILE AD HOC NETWORKS</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr A Unnikrishnan
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">DEEPA ELIZAPBETH GEORGE</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">4/5/2018</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">DEVELOPMENT AND EVALUATION OF MULTI SENSOR DATA FUSION ALGORITHAMS FOR TARGET TRACKING</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr A Unnikrishnan
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">SMINU IZUDHEEN</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">1/18/2018</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">A Network Approach to improve Link Prediction in Protein-Protein Interaction Network and its Application in Healthcare</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr Sheena Mathew
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">VIMINA E R</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">1/3/2018</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Computational  Frameworks For Efficiency Enhancement of Content Based  Image Retrieval Systems</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr K Paulose Jacob
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">SAJU P JOHN</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2/13/2017</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Trust Based Key Management Schemes for MANET</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr Philip Samuel
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">ANUPAMA SURENDRAN</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2/10/2017</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Program Slicing Techniques for Software Testing</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr Philip Samuel
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">DALEESHA M VISWANATH</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">10/3/2016</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">A Computational Framework for Indian Sign Language Recognition</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr Sumam Mary Idicula
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">PREETHA THERESA JOY</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">5/12/2016</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">DESIGN AND DEVELOPMENT OF COOPERATIVE CACHING FRAMEWORK FOR IMPROVING DATA ACCESSIBILITY IN WIRELESS AD HOC NETWORKS</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr Sumam Mary IdiculaBinsu C Kovoor</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Santhosh Simon</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2016</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dat Aggregation and MAC Layer Approaches for enhanced Energy Efficiency in Large Scale Wiresless Sensor Networks</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr. K. Poulose Jacob
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Reena Murali</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2016</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Soft Computing Approach for Optimization of SIRNA Efficiency Prediction for Post Transcrptional Gene Silencing</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr. David Peter S
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Preetha Theresa Joy</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2016</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Design and Development of Cooperative Caching Framework for Improving Data Accessibility in Wireless Ad Hoc Networks</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr. K Poulose Jacob
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Latha R. Nair</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2015</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Studies on a Syntax Based approach for Translation Between Structurally Different Languages and the Development of a Prototype for Malayalam to English Translation</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr. David Peter S
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Sonia Sunny</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2015</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">A Hybrid Architecture for Recognizing Speech Signals in Malayalam</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr. David Peter S
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Vineetha S</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2015</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Reconstruction of Gene Regulatory Network from Expression Profile of Plasma RNA Data of Colorectal Cancer Patients Using Soft Computing Techniques</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr. Sumam Mary Idicula
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Bindiya M. Varghese</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2014</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Development of Hierarchical Clustering Techniques for Gridded Data from Mixed Data Sequences</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr. Unnikrishnan A
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Litta A. J</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2013</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Computational Models for the Prediction of Severe Thunderstorms over Indian Region</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr. Sumam Mary Idicula
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Sreeraj M</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2013</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">A Writer Identification System for Handwritten Malayalam Documents</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr. Sumam Mary Idicula
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Sudeep Elayidom M</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2013</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Design and Development of Data Mining Models for the Prediction of Manpower Placement in the Technical Domain</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr. Sumam Mary Idicula
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Bindu M.S</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2012</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">(Ict) On Professional Development and Educational Needs of Library Professionals in the Universities of Kerala</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr. Sumam Mary Idicula
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Binu G S</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2012</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Energy Management in Wireless Sensor Networks: A Crosslayer</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;"> Channel Adaptive Approach Towards Performance Optimization</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Mariamma Chacko</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2012</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Validation and Optimization of Embedded system code as Architecture Oriented Approach</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr. K. Poulose Jacob
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Shyama Das</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2012</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Mean Squared Residue Based Biclustering Algorithms for the Analysis of Gene Expression Data</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr. Sumam Mary Idicula
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">G Santhoshkumar</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2011</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Energy-Efficient Cluster Based Routing Schemes for static and Mobile Sensor Networks</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr. K Poulose Jacob
</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Shibu Ray S</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2010</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">A Study on The Information Seeking Behavior of Science and Technology Teachers and Researchers of Cochin University of Science and Technology</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr. M D Baby</div></td></tr><tr><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Rekha K James</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left;">2010</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Design and Synthesis of Efficient MAC Architectures for High Speed Decimal Processor</div></td><td style="border-width: 2px; border-bottom-style: solid; border-color: black;"><div style="text-align: left; width: 90%;">Dr. K Poulose Jacob
</div></td></tr><tr><td><div class="mb-3"><div style="text-align: left; width: 90%;">Susan Mathew</div></td><td><div style="text-align: left;">2010</div></td><td><div style="text-align: left; width: 90%;">Impact of Information Communication Technologies</div></td><td><div style="text-align: left; width: 90%;">Dr. M D Baby</div></td></div></tr></tbody></table>

		  </td>
                </tr>
               
              </tbody></table></td>
        </tr>
        <tr> </tr>
      </tbody>
    </table></td>
  </tr>
            </tbody>
        </table>
    </div>


  <?php	include('footer.php'); ?>